# Generated by Django 3.2.6 on 2021-08-20 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField()),
                ('nbuses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('busid', models.IntegerField()),
                ('buscategory', models.CharField(max_length=100)),
                ('bustype', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=30)),
                ('latideal', models.FloatField()),
                ('lngideal', models.FloatField()),
                ('affiliationlevel', models.CharField(max_length=100)),
                ('havegps', models.IntegerField()),
                ('latreal', models.FloatField()),
                ('lngreal', models.FloatField()),
                ('lastupdated', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductorid', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=30)),
                ('passhash', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeid', models.IntegerField()),
                ('placename', models.CharField(max_length=1000)),
                ('popularity', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('sotptype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origt', models.TimeField()),
                ('destt', models.TimeField()),
                ('getints', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None), size=None)),
                ('getoutts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None), size=None)),
                ('routeid', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=models.SET('DELETED'), to='user.bus')),
                ('conductor', models.ForeignKey(on_delete=models.SET('UNASSIGNED'), to='user.conductor')),
                ('dest', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='routedestplace', to='user.place')),
                ('orig', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='routeorigplace', to='user.place')),
                ('stops', models.ManyToManyField(related_name='routestopsplaces', to='user.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=3000)),
                ('passhash', models.CharField(max_length=1000)),
                ('ownerid', models.IntegerField()),
                ('ownedbuses', models.ManyToManyField(related_name='ownerownedbusesbus', to='user.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='MKUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('uid', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('logincreds', models.CharField(max_length=1000)),
                ('bookings', models.ManyToManyField(to='user.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getint', models.TimeField()),
                ('getoutt', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='connectbus', to='user.bus')),
                ('dest', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='connectiondest', to='user.place')),
                ('origin', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='connectionorigin', to='user.place')),
                ('route', models.ForeignKey(on_delete=models.SET('DELETED'), to='user.route')),
                ('routedest', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='connectfinaldest', to='user.place')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='assignedroutes',
            field=models.ManyToManyField(related_name='conductorassignedrouteroute', to='user.Route'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='employer',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='user.owner'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='presentbus',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), related_name='conductorpresentbus', to='user.bus'),
        ),
        migrations.AddField(
            model_name='bus',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='user.owner'),
        ),
        migrations.AddField(
            model_name='bus',
            name='presentconductor',
            field=models.ForeignKey(on_delete=models.SET('UNASSIGNED'), to='user.conductor'),
        ),
        migrations.AddField(
            model_name='bus',
            name='routes',
            field=models.ManyToManyField(related_name='busroutesroute', to='user.Route'),
        ),
        migrations.AddField(
            model_name='booking',
            name='connections',
            field=models.ManyToManyField(to='user.Connection'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dest',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), related_name='bookingdest', to='user.place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), related_name='bookingorigin', to='user.place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='user.mkuser'),
        ),
    ]
