# Generated by Django 3.2.6 on 2021-08-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='sotptype',
            new_name='stoptype',
        ),
    ]
