# Generated by Django 3.2.6 on 2021-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210821_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gplaceid',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
