# Generated by Django 3.2.6 on 2021-08-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_place_gplaceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='assignedroutes',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='presentbus',
        ),
    ]
