# Generated by Django 3.2.6 on 2021-08-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210821_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
    ]
