# Generated by Django 3.2.6 on 2021-08-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_route_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getint', models.TimeField()),
                ('getoutt', models.TimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='user.BusInStop', to='user.Place'),
        ),
    ]
