# Generated by Django 3.2.6 on 2021-08-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_businstop_finaldest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mkuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='busid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mkuser',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
