# Generated by Django 3.2.6 on 2021-08-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20210821_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businstop',
            name='id',
        ),
        migrations.AddField(
            model_name='businstop',
            name='businstopid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
