# Generated by Django 3.2.6 on 2021-08-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210821_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businstop',
            name='businstopid',
            field=models.CharField(default='1', max_length=200, primary_key=True, serialize=False),
        ),
    ]
