# Generated by Django 3.2.6 on 2021-08-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_businstop_businstopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('fromgetint', models.TimeField()),
                ('togetint', models.TimeField()),
                ('fromgetoutt', models.TimeField()),
                ('togetoutt', models.TimeField()),
                ('pathid', models.IntegerField(primary_key=True, serialize=False)),
                ('getinp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getinp', to='user.place')),
                ('getoutp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getoutp', to='user.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.route')),
            ],
        ),
    ]
