# Generated by Django 3.2.6 on 2021-08-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_place_departures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='connections',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
