# Generated by Django 3.2.6 on 2021-08-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20210822_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='departures',
        ),
        migrations.AddField(
            model_name='place',
            name='pgetinp',
            field=models.ManyToManyField(related_name='_user_place_pgetinp_+', through='user.Connect', to='user.Place'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='getinp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='user.place'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='getoutp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='user.place'),
        ),
    ]
