# Generated by Django 3.2.6 on 2021-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20210822_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='pgetinp',
        ),
        migrations.AddField(
            model_name='place',
            name='departadd',
            field=models.ManyToManyField(related_name='_user_place_departadd_+', through='user.Connect', to='user.Place'),
        ),
    ]
