# Generated by Django 3.2.6 on 2021-08-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_connect_pathid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businstop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='user.place'),
        ),
    ]
