# Generated by Django 3.2.6 on 2021-08-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_businstop_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='stops',
            new_name='stopsadd',
        ),
        migrations.AlterField(
            model_name='businstop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='user.route'),
        ),
    ]
