# Generated by Django 3.2.6 on 2021-08-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20210822_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connects', to='user.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), related_name='routes', to='user.bus'),
        ),
    ]
