# Generated by Django 3.2.6 on 2021-08-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20210822_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect',
            old_name='pathid',
            new_name='connectid',
        ),
    ]
