# Generated by Django 3.2.6 on 2021-08-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_alter_route_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getint', models.TimeField()),
                ('getoutt', models.TimeField()),
                ('price', models.IntegerField()),
                ('getinp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultgetinp', to='user.place')),
                ('getoutp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultgetoutp', to='user.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.route')),
            ],
        ),
    ]
