# Generated by Django 3.2.6 on 2021-08-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_singlesearchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='price',
            field=models.IntegerField(default=99),
        ),
    ]
