# Generated by Django 3.2.6 on 2021-08-22 23:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_connect_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='lastupdated',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='businstop',
            name='finaldesttime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='businstop',
            name='getint',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='businstop',
            name='getoutt',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='connect',
            name='fromgetint',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='connect',
            name='fromgetoutt',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='connect',
            name='togetint',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='connect',
            name='togetoutt',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='destt',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='getints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='getoutts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='origt',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='singlesearchresult',
            name='getint',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='singlesearchresult',
            name='getoutt',
            field=models.TimeField(),
        ),
    ]
