# Generated by Django 3.2.6 on 2021-08-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='nstops',
            field=models.IntegerField(default=1),
        ),
    ]
