# Generated by Django 3.2.6 on 2021-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20210823_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='categoryname',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
    ]
