# Generated by Django 3.2.6 on 2021-08-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_bus_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='checkifstand',
            field=models.IntegerField(default=0),
        ),
    ]
