# Generated by Django 3.2.6 on 2021-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_rename_checkifstand_connect_isgetinpstand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublesearchresult',
            name='id',
        ),
        migrations.AddField(
            model_name='doublesearchresult',
            name='con1con2',
            field=models.CharField(default='UNK', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
