# Generated by Django 3.2.6 on 2021-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20210824_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublesearchresult',
            name='con1con2',
        ),
        migrations.AddField(
            model_name='doublesearchresult',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
