# Generated by Django 3.2.6 on 2021-08-26 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20210824_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='searchtoreach',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doublesearchresult',
            name='searchtoreach',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
