# Generated by Django 3.2.6 on 2021-08-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20210826_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='searchtoreach',
        ),
    ]
