# Generated by Django 3.2.6 on 2021-08-26 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_remove_connect_searchtoreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleSearchResult',
            fields=[
                ('fromgetint', models.DateTimeField()),
                ('togetint', models.DateTimeField()),
                ('fromgetoutt', models.DateTimeField()),
                ('togetoutt', models.DateTimeField()),
                ('connectid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=99)),
                ('isgetinpstand', models.IntegerField(default=0)),
                ('searchtoreach', models.DateTimeField(default=django.utils.timezone.now)),
                ('getinp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departforisnglesearch', to='user.place')),
                ('getoutp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriveforsinglesearch', to='user.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeforsinglesearch', to='user.route')),
            ],
        ),
    ]
